### ISSUE TITLE
Cannot read property 'dependencies' of undefined

### ISSUE THREAD

**Issue by xenogenesi** [tivac/amd-script#1]
Hi @tivac , thanks for this nice solution, I'm looking forward for rollup to support the code splitting for the iife format but I don't think is gonna happen any time soon.

I'm trying amd-script with [rollup-starter-code-splitting](https://github.com/rollup/rollup-starter-code-splitting), modified the project to output only amd, disabled dynamic imports, changed the code to statically import `apply()` (the generated amd looks fine), modified index.html as below (removing any old js):

	<script src="amd-script.js"></script>
	<script src="./amd/chunk1.js"></script>
	<script src="./amd/main-a.js"></script>
	<script src="./amd/main-b.js"></script>
	<script>
		require("./amd/main-a.js");
		require("./amd/main-b.js");
	</script>

but I'm getting this error (I've added the inspecting message):

    inspecting:./amd/main-a.js
    amd-script.js:45 inspecting:./chunk1.js
    amd-script.js:47 Uncaught TypeError: Cannot read property 'dependencies' of undefined
        at require (amd-script.js:47)
        at functions.(:5000/anonymous function).functions.(anonymous function).dependencies.map (http://localhost:5000/amd-script.js:60:24)
        at Array.map (<anonymous>)
        at require (amd-script.js:47)
        at (index):32
    require @ amd-script.js:47
    functions.(anonymous function).functions.(anonymous function).dependencies.map @ amd-script.js:60
    require @ amd-script.js:47
    (anonymous) @ (index):32

here the definition of main-a.js

    define(['./chunk1.js'], function (__chunk1_js) { 'use strict';

and chunk1.js

    define(['exports'], function (exports) { 'use strict';

I'm looking into it but any hint would be appreciated

**Comment by xenogenesi** [comment]
Sorry, just looking at the `define` made me think the ./amd build directory I'm using could be the problem and in fact it is, so either I use the root directory or find a way with rollup to use the same path in the generated `define`.

**Comment by tivac** [comment]
The paths will need to match, yeah. You could rewrite them using a regex or something if needed. Right now there's clearly no code to handle that situation because it'd add a lot of complexity.

**Comment by xenogenesi** [comment]
Thanks for the suggestion, perhaps would be nice to have a callback, but I don't see any nice way to pass it without using globals. If you want to close the issue is ok for me, thanks again

**Comment by tivac** [comment]
We use a rollup plugin to copy the `index.html` into our `./dist` folder so that references don't need to include filepaths. Dunno if it helps, but seems to work ok for us!
